In [83]:
import numpy as np

### 1

In [84]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [85]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [86]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### 2

In [87]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### 3

In [88]:
b = np.array(a_centered[:, 0].copy())
b

array([-1.,  0.,  1.,  1., -1.])

In [89]:
c = np.array(a_centered[:, 1].copy())
c

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [90]:
a_centered_sp = np.dot(b, c)
a_centered_sp

8.0

In [91]:
N = a.shape[0]
result = a_centered_sp / (N - 1)
result

2.0